export const ADD_USER = `
  mutation($email:String!,$username:String!,$image:String!){
    register(userInput:{email:$email,username:$username,image:$image}){
      error{
        message
      }
      status
      data{
        id
        email
        username
        image
        role
        cart{
          id
          quantity
          itemId
        }
        createdAt
        updatedAt
      }
    }
  }
`

export const GET_USER = `
query($email:String!){
  logIn(email:$email){
    error{
      message
    }
    status
    data{
      id
      email
      username
      image
      role
      cart{
        id
        quantity
        itemId
      }
    }
  }
}
`

export const LOGEDIN_USER = `
  query($email:String!){
    getLogedInUser(email:$email){
      error{
        message
      }
      status
      data{
        id
        email
        username
        image
        role
        cart{
          id
          quantity
          itemId
        }
        createdAt
        updatedAt
      }
    }
  }
`
